services:
  postgres:
    image: postgres:12-bullseye
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynet

  api-1:
    image: sebacassone/prestabanco-backend
    container_name: api-1
    restart: always
    ports:
      - "8001:8000"
    networks:
      - mynet
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

  api-2:
    image: sebacassone/prestabanco-backend
    container_name: api-2
    restart: always
    ports:
      - "8002:8000"
    networks:
      - mynet
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

  api-3:
    image: sebacassone/prestabanco-backend
    container_name: api-3
    restart: always
    ports:
      - "8003:8000"
    networks:
      - mynet
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynet

  frontend:
    image: sebacassone/prestabanco-frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
